@Users.API_HostAddress = http://localhost:5000
@Catalog.Api_HostAddress = http://localhost:5025
@Kong_HostAddress = http://localhost:8000

### Principais operações da API de catálogo de jogos
### 1. Autenticar e obter token
# @name login
POST {{Kong_HostAddress}}/api/users/auth
Content-Type: application/json

{
  "email": "admin@fiapcloud.com.br",
  "password": "admin"
}

###

### 2. Cadastrar um novo jogo
POST {{Kong_HostAddress }}/game/
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Diablo IV",
  "description": "Diablo",
  "publisher": "Blizzard Activision",
  "genres": [{"name": "RPG"}],
  "releaseDate": "2020-12-01",
  "price": 39.99
}
###

### 3. Adicionar um jogo ao catálogo de um usuário
POST {{Kong_HostAddress}}/catalog/
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "gameId": "6a8b03133012ceb88322f1e6",
  "userEmail": "admin@fiapcloud.com.br",
  "price": 19.90
}
###

### 4. Consultar jogos no catalogo do usuário
GET {{Kong_HostAddress}}/catalog/1
Authorization: Bearer {{login.response.body.$.token}}
Accept: application/json

###

### Demais operações:

### Obter todos os jogos
GET {{Kong_HostAddress}}/game/
Authorization: Bearer {{login.response.body.$.token}}
Accept: application/json
###

### Obter um jogo específico
GET {{Kong_HostAddress}}/game/6a899d5bc6debd5e03eceef6
Authorization: Bearer {{login.response.body.$.token}}
Accept: application/json
###

### Atualizar um jogo existente
PUT {{Kong_HostAddress}}/game/6a89cfa4ae0c1c1eaec0839b
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Resident Evil X",
  "description": "A new Resident Evil Series game",
  "publisher": "Capcom",
  "releaseDate": "2026-02-27T00:00:00Z",
  "price": 70,
  "status": "ACTIVE"
}
###

### Remover um jogo
DELETE {{Kong_HostAddress}}/game/6a84f2a42821cd3184ebc821
Authorization: Bearer {{login.response.body.$.token}}
Accept: application/json
###