<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3aaf2f11-ee8f-4b9e-90b2-97df0a3ffa17</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.7.400.30" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400.30" />
    <PackageReference Include="MassTransit.AmazonSQS" Version="8.3.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fcg.Contracts\Fcg.Contracts.csproj" />
  </ItemGroup>

</Project>
