apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: catalog-api
          image: fcgpostech.azurecr.io/catalog-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
              
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST

            - name: PAYMENTS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENTS_TOPIC

            - name: ORDERS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ORDERS_TOPIC

            - name: MONGODB_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_DB  
                  
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_KEY

            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_ISSUER
            
            - name: KeyVaultUri
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KeyVaultUri

            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AZURE_TENANT_ID

            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AZURE_CLIENT_ID

            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AZURE_CLIENT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: ClusterIP
  selector:
    app: catalog-api
  ports:
    - port: 8080
      targetPort: 8080